apiVersion: v2
name: hlib
description: Helm library chart for common Kubernetes templates
type: library
kubeVersion: '>=1.32.0-0'
version: 0.0.3
home: https://github.com/anatolek/helm-charts
icon: https://raw.githubusercontent.com/anatolek/helm-charts/main/charts/hlib/img/icon.png
sources:
  - https://github.com/anatolek/helm-charts
maintainers:
  - name: Anatolii Pedchenko
    email: anatolek@ukr.net
keywords:
  - helm
  - library
  - kubernetes
  - templates
  - deployment
  - cronjob
  - service
  - ingress
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - kind: added
      description: README.md is added to the chart
  artifacthub.io/links: |
    - name: GitHub Repository
      url: https://github.com/anatolek/helm-charts
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "false"
