apiVersion: v2
appVersion: "1.29"
description: A Helm chart for deploying envVars application
keywords:
- envVars
name: envVars
type: application
version: "1.29"
icon: https://raw.githubusercontent.com/anatolek/helm-charts/main/charts/hlib/img/icon.png
dependencies:
- name: hlib
  version: ">= 0.0.0"
  repository: https://anatolek.github.io/helm-charts
